︠1190c54a-0f54-4a99-a653-a0a377194c7cs︠
%attach Graph_Generating_Methods.sage
%attach General_Methdos.sage
︡5e48b208-f538-4ab2-9228-f92e37cd75de︡{"stderr":"Error in lines 1-1\nTraceback (most recent call last):\n  File \"/cocalc/lib/python3.8/site-packages/smc_sagews/sage_server.py\", line 1230, in execute\n    exec(\n  File \"\", line 1, in <module>\n  File \"/cocalc/lib/python3.8/site-packages/smc_sagews/sage_server.py\", line 1324, in execute_with_code_decorators\n    code = code_decorator(code)\n  File \"sage/misc/lazy_import.pyx\", line 360, in sage.misc.lazy_import.LazyImport.__call__ (build/cythonized/sage/misc/lazy_import.c:4032)\n    return self.get_object()(*args, **kwds)\n  File \"/ext/sage/sage-9.3/local/lib/python3.9/site-packages/sage/repl/attach.py\", line 358, in attach\n    load(filename, globals(), attach=True)\n  File \"/ext/sage/sage-9.3/local/lib/python3.9/site-packages/sage/repl/load.py\", line 266, in load\n    exec(code, globals)\n  File \"/home/user/.sage/temp/project-f37fb78e-a935-489a-a88a-6c914fc0e813/1944/Graph_Generating_Methods.sagejoadkgy7.py\", line 5, in <module>\n    _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_12 = Integer(12); _sage_const_22 = Integer(22); _sage_const_13 = Integer(13); _sage_const_14 = Integer(14); _sage_const_15 = Integer(15); _sage_const_16 = Integer(16); _sage_const_17 = Integer(17); _sage_const_18 = Integer(18); _sage_const_20 = Integer(20); _sage_const_19 = Integer(19); _sage_const_21 = Integer(21); _sage_const_23 = Integer(23)# Import module General_Methods.sage\nNameError: name 'Integer' is not defined\n"}︡{"done":true}

H = Graph({0:[1,2,3]})
# Finds unique induced H-saturated graphs on n = 7, ..., 9 vertices
for i in range(7, 10):
    find_unique_indsat_graphs_def1(n, H)
